### ISSUE TITLE
'locks' inside async/await code

### ISSUE THREAD

**Issue by mmisztal1980** [wojciech12/talk_zero_downtime_deployment_with_kubernetes#5]
Since this code is to be used as an example, I feel it is important to highlight one really bad practice:
- You must not mix System.Threading synchronization primitives such as `lock` with `async/await` code.

The reason is that the async/await code runs on your synchronization context, in this case the default is the ThreadPool which contains N threads that are used to asynchronously execute `Task(s)`. If you `lock`, you effectively lock one of the threads in the threadpool, preventing other async operations from using it, until the lock is released.

Please remove the locks and use [Interlocked](https://docs.microsoft.com/en-us/dotnet/api/system.threading.interlocked?view=netframework-4.7.2) instead.

**Comment by wojciech12** [comment]
@mmisztal1980 Could you provide a PR showing the fix?

**Comment by meanin** [comment]
@wojciech12 Can you assign it to me?

**Comment by meanin** [comment]
Furthermore, @mmisztal1980 I am assuming that I have to use Interlocked for the integer value incrementing/decrementing. What about boolean? Volatile?

**Comment by mmisztal1980** [comment]
@meanin I'd try something like `Interlocked.CompareExchange` -

**Comment by meanin** [comment]
What about SemaphoreSlim?

**Comment by meanin** [comment]
Hi again,
I changed logic to base on `Interlocked.CompareExchange`. @mmisztal1980 Can you check it, please:
https://github.com/meanin/talk_zero_downtime_deployment_with_kubernetes/blob/master/demo_net/ZeroDowntimeDeployment/Middlewares/GracefulShutdownMiddleware.cs
